package com.carlmanning.carlsbrain

import androidx.room.Room
import androidx.room.testing.MigrationTestHelper
import androidx.sqlite.db.framework.FrameworkSQLiteOpenHelperFactory
import androidx.test.ext.junit.runners.AndroidJUnit4
import androidx.test.platform.app.InstrumentationRegistry
import com.carlmanning.carlsbrain.data.local.AppDatabase
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith
import java.io.IOException

/**
 * Verifies every migration in [AppDatabase] against the exported schema JSONs
 * (carlsbrain/schemas/, generated by KSP at build time and committed).
 *
 * `fallbackToDestructiveMigration` was deliberately removed, so a bad migration now fails
 * loudly at runtime instead of wiping the database. These tests catch it before it ships.
 */
@RunWith(AndroidJUnit4::class)
class MigrationTest {

    companion object {
        private const val TEST_DB = "migration-test.db"
        private const val LATEST_VERSION = 22

        /** Every migration registered on the real database builder, in order. */
        private val ALL_MIGRATIONS = arrayOf(
            AppDatabase.MIGRATION_1_2,
            AppDatabase.MIGRATION_2_3,
            AppDatabase.MIGRATION_3_4,
            AppDatabase.MIGRATION_4_5,
            AppDatabase.MIGRATION_5_6,
            AppDatabase.MIGRATION_6_7,
            AppDatabase.MIGRATION_7_8,
            AppDatabase.MIGRATION_8_9,
            AppDatabase.MIGRATION_9_10,
            AppDatabase.MIGRATION_10_11,
            AppDatabase.MIGRATION_11_12,
            AppDatabase.MIGRATION_12_13,
            AppDatabase.MIGRATION_13_14,
            AppDatabase.MIGRATION_14_15,
            AppDatabase.MIGRATION_15_16,
            AppDatabase.MIGRATION_16_17,
            AppDatabase.MIGRATION_17_18,
            AppDatabase.MIGRATION_18_19,
            AppDatabase.MIGRATION_19_20,
            AppDatabase.MIGRATION_20_21,
            AppDatabase.MIGRATION_21_22,
        )
    }

    @get:Rule
    val helper: MigrationTestHelper = MigrationTestHelper(
        InstrumentationRegistry.getInstrumentation(),
        AppDatabase::class.java,
        emptyList(),
        FrameworkSQLiteOpenHelperFactory()
    )

    /**
     * The important one: create the database as it existed at version 1 and walk it all the
     * way to the current version, validating the resulting schema against the exported JSON.
     */
    @Test
    @Throws(IOException::class)
    fun migrateAll_fromVersion1_toLatest() {
        // Creating at v1 writes the v1 schema and closes it; the migrations run below.
        helper.createDatabase(TEST_DB, 1).close()

        helper.runMigrationsAndValidate(TEST_DB, LATEST_VERSION, true, *ALL_MIGRATIONS)
    }

    /**
     * Opens the real Room database class with all migrations registered, which forces Room to
     * validate the on-disk schema produced above against the compiled entity definitions.
     */
    @Test
    @Throws(IOException::class)
    fun realDatabase_opensAfterAllMigrations() {
        helper.createDatabase(TEST_DB, 1).close()
        helper.runMigrationsAndValidate(TEST_DB, LATEST_VERSION, true, *ALL_MIGRATIONS)

        val context = InstrumentationRegistry.getInstrumentation().targetContext
        val db = Room.databaseBuilder(context, AppDatabase::class.java, TEST_DB)
            .addMigrations(*ALL_MIGRATIONS)
            .build()
        try {
            // openHelper.writableDatabase triggers Room's own schema identity check.
            db.openHelper.writableDatabase
        } finally {
            db.close()
        }
    }
}
