package com.carlmanning.carlsbrain

import androidx.room.Room
import androidx.room.testing.MigrationTestHelper
import androidx.sqlite.db.framework.FrameworkSQLiteOpenHelperFactory
import androidx.test.ext.junit.runners.AndroidJUnit4
import androidx.test.platform.app.InstrumentationRegistry
import com.carlmanning.carlsbrain.data.local.AppDatabase
import org.junit.Assume
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith
import java.io.IOException

/**
 * Verifies every migration in [AppDatabase] against the exported schema JSONs
 * (carlsbrain/schemas/, generated by KSP at build time and committed).
 *
 * `fallbackToDestructiveMigration` was deliberately removed, so a bad migration now fails
 * loudly at runtime instead of wiping the database. These tests catch it before it ships.
 */
@RunWith(AndroidJUnit4::class)
class MigrationTest {

    companion object {
        private const val TEST_DB = "migration-test.db"
        private const val LATEST_VERSION = 22

        /** Every migration registered on the real database builder, in order. */
        private val ALL_MIGRATIONS = arrayOf(
            AppDatabase.MIGRATION_1_2,
            AppDatabase.MIGRATION_2_3,
            AppDatabase.MIGRATION_3_4,
            AppDatabase.MIGRATION_4_5,
            AppDatabase.MIGRATION_5_6,
            AppDatabase.MIGRATION_6_7,
            AppDatabase.MIGRATION_7_8,
            AppDatabase.MIGRATION_8_9,
            AppDatabase.MIGRATION_9_10,
            AppDatabase.MIGRATION_10_11,
            AppDatabase.MIGRATION_11_12,
            AppDatabase.MIGRATION_12_13,
            AppDatabase.MIGRATION_13_14,
            AppDatabase.MIGRATION_14_15,
            AppDatabase.MIGRATION_15_16,
            AppDatabase.MIGRATION_16_17,
            AppDatabase.MIGRATION_17_18,
            AppDatabase.MIGRATION_18_19,
            AppDatabase.MIGRATION_19_20,
            AppDatabase.MIGRATION_20_21,
            AppDatabase.MIGRATION_21_22,
        )
    }

    @get:Rule
    val helper: MigrationTestHelper = MigrationTestHelper(
        InstrumentationRegistry.getInstrumentation(),
        AppDatabase::class.java,
        emptyList(),
        FrameworkSQLiteOpenHelperFactory()
    )

    /**
     * Does a schema JSON for [version] exist in the androidTest assets?
     *
     * exportSchema was false for this database's whole history, so only versions exported from
     * now on have a JSON. Tests that need an older one are skipped rather than failed — a suite
     * that is red for a reason unrelated to correctness just teaches you to ignore it.
     */
    private fun schemaExists(version: Int): Boolean {
        val ctx = InstrumentationRegistry.getInstrumentation().context
        val dir = AppDatabase::class.java.canonicalName ?: return false
        return runCatching { ctx.assets.list(dir)?.contains("$version.json") == true }
            .getOrDefault(false)
    }

    /**
     * Validates the current schema against the compiled entities.
     *
     * This is the one that runs today: it catches an entity changed without a matching
     * migration, which is exactly the mistake that used to be swallowed by
     * fallbackToDestructiveMigration and surface to Carl as "the app lost my data".
     */
    @Test
    @Throws(IOException::class)
    fun currentSchema_matchesEntities() {
        Assume.assumeTrue(
            "No $LATEST_VERSION.json yet — build once so KSP exports it, then commit carlsbrain/schemas/",
            schemaExists(LATEST_VERSION)
        )
        helper.createDatabase(TEST_DB, LATEST_VERSION).close()
        helper.runMigrationsAndValidate(TEST_DB, LATEST_VERSION, true)
    }

    /**
     * Walks every migration from v1 to the current version.
     *
     * Skipped until a 1.json exists. It never has: exportSchema was only turned on at v22, so
     * the historical schemas would have to be reconstructed to validate migrations retroactively.
     * From v22 onward each version exports its own JSON, so every *new* migration is covered by
     * [migrateFromPrevious_toLatest] without any of this.
     */
    @Test
    @Throws(IOException::class)
    fun migrateAll_fromVersion1_toLatest() {
        Assume.assumeTrue(
            "No 1.json — historical schemas were never exported, so pre-v22 migrations " +
                "cannot be validated retroactively without reconstructing them.",
            schemaExists(1)
        )
        helper.createDatabase(TEST_DB, 1).close()
        helper.runMigrationsAndValidate(TEST_DB, LATEST_VERSION, true, *ALL_MIGRATIONS)
    }

    /**
     * Validates the most recent migration step. This is the test that protects every future
     * schema change: once v23 exists, this walks v22 to v23 against both exported schemas.
     */
    @Test
    @Throws(IOException::class)
    fun migrateFromPrevious_toLatest() {
        Assume.assumeTrue(
            "Needs both ${LATEST_VERSION - 1}.json and $LATEST_VERSION.json exported.",
            schemaExists(LATEST_VERSION - 1) && schemaExists(LATEST_VERSION)
        )
        helper.createDatabase(TEST_DB, LATEST_VERSION - 1).close()
        helper.runMigrationsAndValidate(TEST_DB, LATEST_VERSION, true, *ALL_MIGRATIONS)
    }

    /**
     * Opens the real Room database class, forcing Room's own identity-hash check of the
     * on-disk schema against the compiled entities.
     */
    @Test
    @Throws(IOException::class)
    fun realDatabase_opens() {
        Assume.assumeTrue(schemaExists(LATEST_VERSION))
        helper.createDatabase(TEST_DB, LATEST_VERSION).close()

        val context = InstrumentationRegistry.getInstrumentation().targetContext
        val db = Room.databaseBuilder(context, AppDatabase::class.java, TEST_DB)
            .addMigrations(*ALL_MIGRATIONS)
            .build()
        try {
            db.openHelper.writableDatabase
        } finally {
            db.close()
        }
    }
}
