package com.carlmanning.carlsbrain

import androidx.room.Room
import androidx.room.testing.MigrationTestHelper
import androidx.sqlite.db.framework.FrameworkSQLiteOpenHelperFactory
import androidx.test.ext.junit.runners.AndroidJUnit4
import androidx.test.platform.app.InstrumentationRegistry
import com.carlmanning.carlsbrain.data.local.AppDatabase
import org.junit.Assert.assertTrue
import org.junit.Assert.fail
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith
import java.io.IOException

/**
 * Verifies every migration in [AppDatabase] against the exported schema JSONs
 * (`carlsbrain/schemas/`, generated by KSP at build time and committed).
 *
 * ## Why this file was rewritten (August 2026)
 *
 * The previous version pinned `LATEST_VERSION = 22` and listed migrations only up to 21→22.
 * The database had since reached 28. So it dutifully created a v22 database, validated it
 * against 22.json, passed, and told us nothing about the six migrations that came after —
 * including the two that had already crashed on launch.
 *
 * Worse, every test was wrapped in `Assume.assumeTrue(schemaExists(...))`. A missing schema
 * meant the test *skipped*, and a skipped test reports green. The suite was structurally
 * incapable of failing.
 *
 * Two rules follow, and both are the point of this file:
 *
 *  1. **Nothing is derived from a hand-maintained version constant.** The set of versions under
 *     test is read from the exported schemas at runtime, so bumping the database and rebuilding
 *     automatically widens the coverage. There is no number here to forget to update.
 *  2. **A missing schema fails, it does not skip.** If KSP has not exported the current version,
 *     that is precisely the state in which a migration bug ships unnoticed, so it is an error
 *     with instructions attached — not a silent pass.
 */
@RunWith(AndroidJUnit4::class)
class MigrationTest {

    companion object {
        private const val TEST_DB = "migration-test.db"

        /**
         * Every migration registered on the real database builder.
         *
         * Kept in step with `AppDatabase.buildDatabase`. A missing entry here shows up as a real
         * failure rather than a gap, because [migrateFromEveryExportedSchema] walks each exported
         * version forward through this list and Room refuses a step it has no migration for.
         */
        private val ALL_MIGRATIONS = arrayOf(
            AppDatabase.MIGRATION_1_2,
            AppDatabase.MIGRATION_2_3,
            AppDatabase.MIGRATION_3_4,
            AppDatabase.MIGRATION_4_5,
            AppDatabase.MIGRATION_5_6,
            AppDatabase.MIGRATION_6_7,
            AppDatabase.MIGRATION_7_8,
            AppDatabase.MIGRATION_8_9,
            AppDatabase.MIGRATION_9_10,
            AppDatabase.MIGRATION_10_11,
            AppDatabase.MIGRATION_11_12,
            AppDatabase.MIGRATION_12_13,
            AppDatabase.MIGRATION_13_14,
            AppDatabase.MIGRATION_14_15,
            AppDatabase.MIGRATION_15_16,
            AppDatabase.MIGRATION_16_17,
            AppDatabase.MIGRATION_17_18,
            AppDatabase.MIGRATION_18_19,
            AppDatabase.MIGRATION_19_20,
            AppDatabase.MIGRATION_20_21,
            AppDatabase.MIGRATION_21_22,
            AppDatabase.MIGRATION_22_23,
            AppDatabase.MIGRATION_23_24,
            AppDatabase.MIGRATION_24_25,
            AppDatabase.MIGRATION_25_26,
            AppDatabase.MIGRATION_26_27,
            AppDatabase.MIGRATION_27_28,
            AppDatabase.MIGRATION_28_29,
        )
    }

    @get:Rule
    val helper: MigrationTestHelper = MigrationTestHelper(
        InstrumentationRegistry.getInstrumentation(),
        AppDatabase::class.java,
        emptyList(),
        FrameworkSQLiteOpenHelperFactory()
    )

    /** Schema versions KSP has exported and someone has committed, ascending. */
    private fun exportedVersions(): List<Int> {
        val ctx = InstrumentationRegistry.getInstrumentation().context
        val dir = AppDatabase::class.java.canonicalName ?: return emptyList()
        return runCatching {
            ctx.assets.list(dir).orEmpty()
                .filter { it.endsWith(".json") }
                .mapNotNull { it.removeSuffix(".json").toIntOrNull() }
                .sorted()
        }.getOrDefault(emptyList())
    }

    /**
     * There must be schemas to test against at all.
     *
     * This is the test that would have caught the state this file was found in: schemas 24, 27
     * and 28 were never committed, so everything downstream had nothing to validate and quietly
     * passed. The message says exactly what to do, because the fix is a build and a `git add`.
     */
    @Test
    fun exportedSchemas_areCommitted() {
        val versions = exportedVersions()
        if (versions.isEmpty()) {
            fail(
                "No schema JSONs found. Build once so KSP exports them, then commit " +
                    "carlsbrain/schemas/ — without them every migration test below is vacuous."
            )
        }
        // At least two, or there is no migration step to walk.
        assertTrue(
            "Only one schema exported (${versions.first()}). Commit the previous version's " +
                "JSON too, or no migration can be validated.",
            versions.size >= 2
        )
    }

    /**
     * Validates the newest exported schema against the compiled entities.
     *
     * Catches an entity changed without a matching migration — the mistake that used to be
     * swallowed by `fallbackToDestructiveMigration` and reached Carl as "the app lost my data",
     * and which more recently shipped as an immediate crash on launch.
     */
    @Test
    @Throws(IOException::class)
    fun currentSchema_matchesEntities() {
        val latest = exportedVersions().lastOrNull()
            ?: return fail("No exported schemas — see exportedSchemas_areCommitted.")
        helper.createDatabase(TEST_DB, latest).close()
        helper.runMigrationsAndValidate(TEST_DB, latest, true)
    }

    /**
     * Walks **every** exported schema forward to the newest one.
     *
     * This is the real coverage, and it widens by itself: export a new version and it is
     * included next run, with no constant to update. It also fails if [ALL_MIGRATIONS] is
     * missing a step, since Room cannot migrate across a gap.
     */
    @Test
    @Throws(IOException::class)
    fun migrateFromEveryExportedSchema() {
        val versions = exportedVersions()
        val latest = versions.lastOrNull()
            ?: return fail("No exported schemas — see exportedSchemas_areCommitted.")

        for (from in versions.dropLast(1)) {
            // A fresh file per step: MigrationTestHelper reuses the database between calls, and
            // a leftover from the previous version would be migrated rather than created.
            InstrumentationRegistry.getInstrumentation().targetContext.deleteDatabase(TEST_DB)
            helper.createDatabase(TEST_DB, from).close()
            helper.runMigrationsAndValidate(TEST_DB, latest, true, *ALL_MIGRATIONS)
        }
    }

    /**
     * Opens the real Room database on top of each exported schema.
     *
     * Stronger than the checks above and immune to any constant in this file: Room performs its
     * own identity-hash comparison of the on-disk schema against the *compiled* entities. If the
     * database version has been bumped without exporting a schema, this is the test that still
     * exercises the new migration, because Room migrates to whatever the code says.
     */
    @Test
    @Throws(IOException::class)
    fun realDatabase_opensFromEveryExportedSchema() {
        val context = InstrumentationRegistry.getInstrumentation().targetContext
        val versions = exportedVersions()
        if (versions.isEmpty()) return fail("No exported schemas — see exportedSchemas_areCommitted.")

        for (from in versions) {
            context.deleteDatabase(TEST_DB)
            helper.createDatabase(TEST_DB, from).close()

            val db = Room.databaseBuilder(context, AppDatabase::class.java, TEST_DB)
                .addMigrations(*ALL_MIGRATIONS)
                .build()
            try {
                db.openHelper.writableDatabase
            } finally {
                db.close()
            }
        }
    }
}
